services:
  n8n:
    image: n8nio/n8n:2.6.1
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    # IMPORTANTE: Sin --hostname, Ngrok pondrá HTTPS automático
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=38szQzqkHdAIs5IVRcTtVMUkhld_3ndWUYtJHhx6u6yhfjEZA
    depends_on:
      - n8n
    restart: always